title = "Immunité specifique"
description = "Learn about immunité specifique"
xp_reward = 120
[[section]]
id = "intro"
type = "SUMMARY"
title = "What is immunité specifique?"
[section.summary]
markdown_text = """
# Welcome to immunité specifique!
**Immunité specifique** is a way that the body kills specifique microbes.
"""
image_urls = ["https://imgs.search.brave.com/zBgRoM_kw-VER2sDKVx66bQvYjqdhan74qghJMBOaO8/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9tc3Nz/LmdvdXYucWMuY2Ev/cHJvZmVzc2lvbm5l/bHMvaW1hZ2VzL3Bp/cS9jZWxsdWxlcy5w/bmc"]
[[section]]
id = "quiz"
type = "QUIZ"
title = "Test Yourself"
[section.quiz]
passing_score_percent = 70
[[section.quiz.question]]
id ="q1"
text = "no clue what to put here so the correct answer is chicken"
type = "MULTIPLE_CHOICE"
options = ["Atom", "Beef", "Something", "Chicken"]
correct_answer_index = 3
weight = 1
feedback = "i'm biased to chickens that's why it's the correct answer"
[[section.quiz.question]]
id ="q2"
text = "no clue what to put here x2 so the correct answer is uhhh atom now"
type = "MULTIPLE_CHOICE"
options = ["Atom", "Beef", "Something", "Chicken"]
correct_answer_index = 0
weight = 1
feedback = "i'm not biased to atoms but i chose chicken last time so i have to choose something else now"
