title = "Microbes"
description = "Learn about all the types of microbes"
xp_reward = 120
[[section]]
id = "intro"
type = "SUMMARY"
title = "What are microbes?"
[section.summary]
markdown_text = """
# Welcome to Biology!
Microbes are something **idk**.
"""
image_urls = []
[[section]]
id = "quiz"
type = "QUIZ"
title = "Test Yourself"
[section.quiz]
passing_score_percent = 70
[[section.quiz.question]]
id ="q1"
text = "Which one of these is NOT a type of microbe?"
type = "MULTIPLE_CHOICE"
options = ["Virus", "Bacterie", "Molecule", "Protozoaire"]
correct_answer_index = 2
weight = 1
feedback = "Correct! The Molecule is not a type of microbe!"
