title = "Microbes"
[[section]]
id = "intro"
type = "SUMMARY"
title = "What are microbes?"
[section.summary]
markdown_text = """
# Welcome to Biology!
Microbes are something **idk**.
"""
image_urls = [""]
[[section]]
id = "quiz"
type = "QUIZ"
title = "Test Yourself"
[section.quiz]
passing_score_percent = 70
[[section.quiz.question]]
id ="q1"
text = "Which one of these is NOT a type of microbe?"
type = "MULTIPLE_CHOICE"
options = ["Virus", "Bacterie", "Molecule", "Protozoaire"]
correct_answer_index = 2
weight = 1
feedback = "The Molecule is not a type of microbe because it's (insert explanation here)!"
[[section.quiz.question]]
id ="q2"
text = "I can't think of anything honestly, just choose protozaire"
type = "MULTIPLE_CHOICE"
options = ["Virus", "Bacterie", "Molecule", "Protozoaire"]
correct_answer_index = 3
weight = 1
feedback = "you're right! don't ask why me why though"
